### ISSUE TITLE
Feature Request: Unregister Listeners / Consumers

### ISSUE THREAD

**Issue by SirMangler** [PhilippHeuer/events4j#1]
As the title suggests.
`getClientHelper().disableFollowEventListener()`
`getClientHelper().disableStreamEventListener()`
`getEventManager().unregisterListener()`

Would be very helpful, thanks!

**Comment by PhilippHeuer** [comment]
Changed the title to `getEventManager().unregisterListener()`, i think thats a great idea.

The other 2 requests are more of a feature request for twitch4j, i will add them to my todo list.

**Comment by PhilippHeuer** [comment]
This feature was added in the latest release for all modules (that now return a disposable when registering).
