### ISSUE TITLE
ReactorEventHandler.subscriptions is never written to

### ISSUE THREAD

**Issue by iProdigy** [PhilippHeuer/events4j#11]
https://github.com/PhilippHeuer/events4j/blob/master/handler-reactor/src/main/java/com/github/philippheuer/events4j/reactor/ReactorEventHandler.java#L45

~~Also, if this is changed so that the list is written to, it should be surrounded by a synchronized wrapper or switched to a concurrent implementation~~

**Comment by PhilippHeuer** [comment]
`subscriptions` was removed.
