### ISSUE TITLE
Bintray will stop satisfying requests soon

### ISSUE THREAD

**Issue by Kek5chen** [PhilippHeuer/events4j#13]
Hello,

As stated here: [https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/](url)

Bintray will stop satisfying requests as they will be shutting down their services by the first of May.

I noticed this as your bintray resource already shoots a 403.
Maybe you could switch to another hosting solution and provide that as the new maven / gradle repo?

I would really appreciate it as i luckily had a copy of twitch4j on my harddrive but i never used events4j so i tried pulling it with maven, which.. didnt work as i said earlier and therefore i have to compile it from source now.

I suggest doing what i just wrote not only for this, but every single one of your project using BinTray, JCenter, GoCenter or ChartCenter as repo hosting.

Have a pleasant day,
kek5chen

**Comment by PhilippHeuer** [comment]
Hi @Kek5chen ,

thanks for the message.

We have migrated twitch4j and all dependencies to mavenCentral, including events4j -> https://search.maven.org/search?q=com.github.philippheuer.events4j
There are some exceptions with older versions that didn't fullfill all requirements of mavenCentral yet, but this should only affect the 1.0.0-alpha versions and earlier.

But i seem to have forgotten to update the docs in some projects, as here in events4j.
You should be fine, if you add mavenCentral as repository.
